export enum SagaState {
  PENDING = 'PENDING',
  INVENTORY_PENDING = 'INVENTORY_PENDING',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  COMPENSATING = 'COMPENSATING',
  CONFIRMED = 'CONFIRMED',
  FAILED = 'FAILED',
}
